### ISSUE TITLE
Optional buildDate in output

### ISSUE THREAD

**Issue by andreasvirkus** [maxnowack/node-podcast#16]
Hi!

I'm writing a Metalsmith plugin/wrapper for your package (https://github.com/andreasvirkus/metalsmith-podcast) and was wondering if you'd consider an additional option to hide the `lastBuildDate` from the output (would default to being included)?

It'd make it easier to write tests for the plugin (currently trying to use `asset-dir-equal`) and it'd make it easier to commit the expected build results to the repo.

Willing to make a PR about this if you'd accept it.

Best,
Andreas

**Comment by maxnowack** [comment]
I think `lastBuildDate` is pretty common in RSS and also in podcast feeds. Yes, create a PR and I will accept it :)

**Comment by maxnowack** [comment]
`lastBuildDate` is coming from the [`rss` package](https://www.npmjs.com/package/rss).
I'll close this issue, since it can't be fixed in this repository.
Hint: You can use [mockdate](https://www.npmjs.com/package/mockdate) for testing ;)
