### ISSUE TITLE
Deployment on npm is broken

### ISSUE THREAD

**Issue by dariusk** [maxnowack/node-podcast#22]
When I do `npm install podcast` and inspect the contents of the package that was downloaded I see the following:

![image](https://user-images.githubusercontent.com/266454/35235960-8ce72d48-ff5a-11e7-8083-15038f312358.png)

It looks to me like there is supposed to be a pre-publish step where a `dist/` directory is created, but it's not in the package at all.

I believe what you need to do is create an empty `.npmignore` file in the root directory and then `dist/` will be, well, distributed. ("If both files exist and a file is ignored by .gitignore but not by .npmignore then it will be included." ([docs](https://docs.npmjs.com/cli/publish))) This way, when you run `npm publish`, it will include the `dist/` files since they are not explicitly listed in `.npmignore`, but it will remain ignored by git itself and keep the repo clean.

**Comment by maxnowack** [comment]
I've fixed this with v1.0.1 (4437f2e2bc6c540fa0decd330233f134126d6fe9). I'm using the [`files` section](https://docs.npmjs.com/files/package.json#files) of the `package.json` to specify the files inside the npm build instead of a `.npmignore` file.
I can confirm that v1.0.0 is broken, but v1.0.1 should work

**Comment by maxnowack** [comment]
@dariusk I'm [targeting node@6.12.3](https://github.com/maxnowack/node-podcast/blob/master/package.json#L50) with babel. Which node version do you use?

**Comment by dariusk** [comment]
I'm using node@8.1.1 currently.

**Comment by dariusk** [comment]
Okay, for whatever reason my build is no longer failing. I'll be proactive and close this :)
