### ISSUE TITLE
Missing code paths in release build

### ISSUE THREAD

**Issue by s-kashif** [maxnowack/node-podcast#38]
Just fyi, not sure how but this line of code in index.js https://github.com/maxnowack/node-podcast/blob/master/src/index.js#L99 is not included in the code releases. 

Steps:
1. Open any of the release zips and check index.js (try finding "content") -> Not there
Or
2. Check the npm release. Same issue

**Comment by maxnowack** [comment]
I'm not sure what you mean. I've checked the release zip and the current npm version (`1.2.0`).
Which version have you tried?
