### ISSUE TITLE
iTunes Categories do not work

### ISSUE THREAD

**Issue by SleepyBandit** [maxnowack/node-podcast#4]
itunes categories do not actually work.  It appears that you build an array and then never iterate over it to post the categories to the channel.  You can modify the code to include a .foreach but there is an underlying issue with the recursive buildiTunesCategories function you use to create subcat items.

the first modification I made was to create the foreach.
```javascript
    //ifTruePush(typeof(data.itunesCategory)!="undefined", channel, buildiTunesCategories(data.itunesCategory)); // YOUR OLD CODE

   // REPLACEMENT
    if (typeof(data.itunesCategory)!="undefined") {
        var items = buildiTunesCategories(data.itunesCategory);
            items.forEach(function(item) {
                channel.push(item);
            });
    }
```
this will still create an incorrect response if any category has a subcategory. The issue I believe lies in the buildItunesCategories function.  Its a clever recursive function, but I believe JavaScripts asynchronous nature is the culprit for the incorrect responses.

When you make a call to the same function from within the function when pushing to the array, it ends up pushing nothing since it didn't have time to generate the value before being pushed.

To fix this, I made the following changes to the buildItunesCategories function;
```javascript
            if(categories[i].subcats)
            {
                var subcatItems; //new code
                // Second for loop to iterate over submit items.
               // This will only work for single nested subcats, subcats of subcats are ignored
                for(var n=0; n<categories[i].subcats.length; n++) { 
                    if (n === 0) {
                        subcatItems = {'itunes:category': { _attr: {text: categories[i].subcats[n].text }}};
                    } else {
                        subcatItems = subcatItems, {'itunes:category': { _attr: {text: categories[i].subcats[n].text }}};
                    }
                }
                var item = {'itunes:category': [{ _attr: { text: categories[i].text}}, subcatItems]}; //add subcat items...
                arr.push(item); //...then push to array
                //arr.push({'itunes:category': [{ _attr: { text: categories[i].text}}, buildiTunesCategories(categories[i].subcats)]}); //Original code no longer used
            }
```
This will work.... kind of.  The second for loop has issues and it doesn't seem to actually do any more than 1 sub category.  But for 1 sub category of each category it will format properly.  I will see if I have more time later to keep working on it, but it is late and I've got other things I need to finish right now.  Figured if I posted this here it may help.

**Comment by maxnowack** [comment]
should work in version  `0.2.0`
