### ISSUE TITLE
itunes:explicit should be optional with values 'true' or 'false' , not compulsory with 'Yes' or 'No'

### ISSUE THREAD

**Issue by tripper54** [maxnowack/node-podcast#41]
Currently this library accepts a boolean for itunesExplicit, and casts this to "Yes" or "No", defaulting to "No" if no value is set.

According to the Apple docs the values should be 'true' or 'false':
https://help.apple.com/itc/podcasts_connect/#/itcb54353390

We should also be able to not publish this tag, indicating that the content is not rated.

**Comment by JumpLink** [comment]
@tripper54 is fixed in master but currently not yet published on npm

**Comment by connorjclark** [comment]
Is there anything we could assist with to create a new release?

**Comment by maxnowack** [comment]
@JumpLink you should have access for publish new versions on npm. Do you need some help with that?

**Comment by JumpLink** [comment]
@maxnowack Thank you, I think I do not need help with that, I contact you if I need help. But I will make some changes to the code before I publish a new version.

**Comment by JumpLink** [comment]
@maxnowack @connorjclark New release is published
