### ISSUE TITLE
Change iTunes explicit tag to be 'yes', 'no', or 'clean'

### ISSUE THREAD

**Issue by audrow** [maxnowack/node-podcast#46]
Hey thanks for making this. It really makes it easier to generate a podcast RSS feed.

One thing that I notice when I use the W3C feed validator (https://validator.w3.org/feed/) on the built XML is that the validator doesn't like `true` or `false` for the `itunes:explicit` tag. It would be nice if instead of a boolean, we could pass ` 'yes' | 'no' | 'clean'`, as suggested by the feed validator. Alternatively, the bool could be turned into 'yes' or 'no'.

![Screen Shot 2022-01-03 at 9 20 00 AM](https://user-images.githubusercontent.com/6635382/147960436-7a4f37f1-ab0c-4294-972e-db10151961c7.png)

For now, I'm using the following work around to get my feed validated.
```javascript
const podcast = new Podcast(feedOptions)
// ...add items for episodes...
const rssXml = podcast
  .buildXml()
  .replace(/<itunes:explicit>false<\/itunes:explicit>/g, '<itunes:explicit>no</itunes:explicit>')
  .replace(/<itunes:explicit>true<\/itunes:explicit>/g, '<itunes:explicit>yes</itunes:explicit>')
```

**Comment by JumpLink** [comment]
Okay so #41 was wrong..

**Comment by toshi-toma** [comment]
Hi @JumpLink 
Do you plan to release the #51 ?

**Comment by JumpLink** [comment]
@toshi-toma yes and done :)

**Comment by toshi-toma** [comment]
@JumpLink 

Thank you :)
