### ISSUE TITLE
Update to README.md file for enclosures

### ISSUE THREAD

**Issue by SleepyBandit** [maxnowack/node-podcast#5]
Just a suggestion,
I was looking to pull the mime type and length for enclosures from my own xml file and was frustrated that this solution looked like it required reading the file itself locally to create that information in a new feed.

Luckily I dug around the code and discovered you included the ability to pass a mime type property and size property instead of a file property.

This would be a very useful option to list in the README.md file.  It could help others know there are more choices for enclosures.

**Comment by maxnowack** [comment]
resolved with #6
