### ISSUE TITLE
Item itunesImage

### ISSUE THREAD

**Issue by dbuezas** [maxnowack/node-podcast#7]
Setting itunesImage on the items doesn't seem to work. Beyond pod doesn't get the podcast images.
The channel image works perfectly

**Comment by maxnowack** [comment]
It works for me with `Instacast`. Maybe `Beyond Pod` doesn't support item images? I don't have an android device, so I can't test it.
Have you checked the generated feed xml, if there is an error?
I don't think there is an issue with this package...

**Comment by dbuezas** [comment]
You're probably right, I started tinkling with the source code to add more tags (<image> and so on) and namespaces but nothing worked (I was using the rss module before and I switched to yours because of this). Other podcasts display the item images in Beyondpod so I don't know what I am doing wrong.

Feed doesn't have any errors as far as I can tell.
Would you be so kind and see if this feed shows images in Instacast?
http://nodejs-cuevanet.rhcloud.com/?s=media-blackout-label/tracks

Thanks a bunch!

**Comment by maxnowack** [comment]
The feed shows images in Instacast:
![image](https://cloud.githubusercontent.com/assets/186073/9856537/9fd32c22-5b15-11e5-952e-0162953b173a.png)

**Comment by dbuezas** [comment]
ok, thank you very much (for both the help and the module!), then it is a beyondpod bug.

**Comment by maxnowack** [comment]
You're welcome!
